# tomcat配置
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: @spring.active@  #多环境
  # thymeleaf 模板配置
  thymeleaf:
    encoding: UTF-8
    suffix: .html
    prefix: classpath:/templates/
    cache: false
    mode: HTML5
  # 上传文件配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  #redis 配置
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        # 最大活跃链接数 默认8
        max-active: 8
        # 最大空闲连接数 默认8
        max-idle: 8
        # 最小空闲连接数 默认0
        min-idle: 0
  mvc:
    favicon:
      enabled: false
  devtools:
    restart:
      enabled: true


# mybatis-plus 配置
mybatis-plus:
  type-aliases-package: com.zhou.plus.busi.entity
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      db-type: mysql
      id-type: id_worker_str
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    cache-enabled: true
    lazyLoadingEnabled: true
    aggressive-lazy-loading: true
    auto-mapping-behavior: partial
    default-executor-type: simple
    map-underscore-to-camel-case: true
    local-cache-scope: session
    jdbc-type-for-null: null
